### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by dhirschfeld**
To hopefully recreate the missing win64/py36 package

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
ping @conda-forge/fs!

**Comment by ReimarBauer** [comment]
Hmm, I've not checked for other PR, I merged the updated v2.0.25 request, please verify if that is working for you

**Comment by dhirschfeld** [comment]
Yep - looks like there's a `win64/py36` build for `2.0.25` - thanks @ReimarBauer!

**Pull request closed without merging**
